apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: helloworld
spec:
  type: LoadBalancer
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000