apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helloworld-pvc
  namespace: helloworld  # Change to your desired namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default  # or specific class used in your AKS cluster
